export const sampleMarkdown = [
  "# 🚀 Welcome to Markdown Converter",
  "",
  "Transform your **Markdown** into beautiful **HTML** in real-time.",
  "",
  "---",
  "",
  "## Features",
  "",
  "- **Live Preview** — See changes instantly as you type",
  "- **Syntax Highlighting** — Code blocks with language support",
  "- **Copy HTML** — One-click copy to clipboard",
  "- **Download** — Export your HTML output",
  "- **Responsive** — Works on desktop and mobile",
  "",
  "## Code Example",
  "",
  "Here's a quick example of a React component:",
  "",
  "```tsx",
  'import { useState } from "react";',
  "",
  "interface Props {",
  "  title: string;",
  "}",
  "",
  "export function Card({ title }: Props) {",
  "  const [count, setCount] = useState(0);",
  "",
  "  return (",
  '    <div className="rounded-2xl border p-4 shadow-sm">',
  "      <h2>{title}</h2>",
  "      <p>Count: {count}</p>",
  '      <button onClick={() => setCount(c => c + 1)}>+</button>',
  "    </div>",
  "  );",
  "}",
  "```",
  "",
  "## Typography Showcase",
  "",
  "### Headings",
  "",
  "# Heading 1",
  "## Heading 2",
  "### Heading 3",
  "#### Heading 4",
  "",
  "### Text Styles",
  "",
  "- **Bold text** for emphasis",
  "- *Italic text* for subtle hints",
  "- ~~Strikethrough~~ for completed items",
  "- `inline code` for short snippets",
  "",
  "### Blockquote",
  "",
  "> The best way to predict the future is to create it.",
  "> &mdash; *Peter Drucker*",
  "",
  "### Table",
  "",
  "| Feature | Status | Priority |",
  "|---------|--------|----------|",
  "| Markdown | &#x2705; Done | High |",
  "| HTML Preview | &#x2705; Done | High |",
  "| Syntax Highlighting | &#x2705; Done | Medium |",
  "| Export PDF | &#x1f6a7; WIP | Low |",
  "",
  "### Task List",
  "",
  "- [x] Build the converter",
  "- [x] Add syntax highlighting",
  "- [ ] Write documentation",
  "- [ ] Add dark mode toggle",
  "",
  "---",
  "",
  "Happy coding! &#x1f389;",
].join("\n");